"""add title to study plans

Revision ID: 12c0523b49d8
Revises: 4490e1ce28fb
Create Date: 2026-09-05 14:26:42.693354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12c0523b49d8'
down_revision: Union[str, Sequence[str], None] = '4490e1ce28fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_plans', sa.Column('title', sa.String(), nullable=False,server_default='Untitled Study Plan'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_plans', 'title')
    # ### end Alembic commands ###
