"""add document associations for quiz, study_plan, cheat_sheet, mind_map

Revision ID: 12e0ec56d529
Revises: 2bb1e3bb3a67
Create Date: 2026-08-22 00:01:10.531395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12e0ec56d529'
down_revision: Union[str, Sequence[str], None] = '2bb1e3bb3a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cheat_sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cheat_sheets_id'), 'cheat_sheets', ['id'], unique=False)
    op.create_table('mind_maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('central_topic', sa.String(), nullable=False),
    sa.Column('structure', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mind_maps_id'), 'mind_maps', ['id'], unique=False)
    op.create_table('cheat_sheet_documents',
    sa.Column('cheat_sheet_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cheat_sheet_id'], ['cheat_sheets.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('cheat_sheet_id', 'document_id')
    )
    op.create_table('mind_map_documents',
    sa.Column('mind_map_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['mind_map_id'], ['mind_maps.id'], ),
    sa.PrimaryKeyConstraint('mind_map_id', 'document_id')
    )
    op.create_table('quiz_documents',
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('quiz_id', 'document_id')
    )
    op.create_table('study_plan_documents',
    sa.Column('study_plan_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['study_plan_id'], ['study_plans.id'], ),
    sa.PrimaryKeyConstraint('study_plan_id', 'document_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_plan_documents')
    op.drop_table('quiz_documents')
    op.drop_table('mind_map_documents')
    op.drop_table('cheat_sheet_documents')
    op.drop_index(op.f('ix_mind_maps_id'), table_name='mind_maps')
    op.drop_table('mind_maps')
    op.drop_index(op.f('ix_cheat_sheets_id'), table_name='cheat_sheets')
    op.drop_table('cheat_sheets')
    # ### end Alembic commands ###
