"""add sources column to message

Revision ID: 2bb1e3bb3a67
Revises: 29c1d0366285
Create Date: 2026-08-19 14:23:02.310667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bb1e3bb3a67'
down_revision: Union[str, Sequence[str], None] = '29c1d0366285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sources', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'sources')
    # ### end Alembic commands ###
