"""add source_type and source_url to documents

Revision ID: 2e99da471ad6
Revises: 6e411003305a
Create Date: 2026-08-10 18:59:19.304171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e99da471ad6'
down_revision: Union[str, Sequence[str], None] = '6e411003305a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('source_type', sa.String(), nullable=False,server_default="pdf"))
    op.add_column('documents', sa.Column('source_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'source_url')
    op.drop_column('documents', 'source_type')
    # ### end Alembic commands ###
