"""flashcards are now multi-dcoument like other output formats

Revision ID: 4490e1ce28fb
Revises: 56671bf704cc
Create Date: 2026-08-22 13:00:00.736413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4490e1ce28fb'
down_revision: Union[str, Sequence[str], None] = '56671bf704cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flashcard_documents',
    sa.Column('flashcard_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['flashcard_id'], ['flashcards.id'], ),
    sa.PrimaryKeyConstraint('flashcard_id', 'document_id')
    )
    op.drop_constraint(op.f('flashcards_document_id_fkey'), 'flashcards', type_='foreignkey')
    op.drop_column('flashcards', 'document_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcards', sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('flashcards_document_id_fkey'), 'flashcards', 'documents', ['document_id'], ['id'])
    op.drop_table('flashcard_documents')
    # ### end Alembic commands ###
