"""remove mind maps

Revision ID: 56671bf704cc
Revises: 12e0ec56d529
Create Date: 2026-08-22 01:11:01.577441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56671bf704cc'
down_revision: Union[str, Sequence[str], None] = '12e0ec56d529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_table('mind_map_documents')
    op.drop_index(op.f('ix_mind_maps_id'), table_name='mind_maps')
    op.drop_table('mind_maps')

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mind_map_documents',
    sa.Column('mind_map_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('mind_map_documents_document_id_fkey')),
    sa.ForeignKeyConstraint(['mind_map_id'], ['mind_maps.id'], name=op.f('mind_map_documents_mind_map_id_fkey')),
    sa.PrimaryKeyConstraint('mind_map_id', 'document_id', name=op.f('mind_map_documents_pkey'))
    )
    op.create_table('mind_maps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('central_topic', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('structure', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('mind_maps_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('mind_maps_pkey'))
    )
    op.create_index(op.f('ix_mind_maps_id'), 'mind_maps', ['id'], unique=False)
    # ### end Alembic commands ###
