"""add type to flashcards

Revision ID: 6cba07d9df68
Revises: 987b44f34303
Create Date: 2026-07-20 18:20:56.039597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cba07d9df68'
down_revision: Union[str, Sequence[str], None] = '987b44f34303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flashcards', sa.Column('type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flashcards', 'type')
    # ### end Alembic commands ###
