"""add solved to quizzes

Revision ID: 6e411003305a
Revises: dfe42db2c00d
Create Date: 2026-07-24 16:12:10.681735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e411003305a'
down_revision: Union[str, Sequence[str], None] = 'dfe42db2c00d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('solved', sa.Boolean(), nullable=False,server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'solved')
    # ### end Alembic commands ###
