"""add completed to study plan items

Revision ID: 987b44f34303
Revises: 4284c2b05290
Create Date: 2026-07-20 16:28:23.968517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '987b44f34303'
down_revision: Union[str, Sequence[str], None] = '4284c2b05290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_plan_items', sa.Column('completed', sa.Boolean(), nullable=False, server_default='false'))    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_plan_items', 'completed')
    # ### end Alembic commands ###
