"""add study plans

Revision ID: b7eca990699e
Revises: ba732ba4559b
Create Date: 2026-07-20 15:35:42.254895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7eca990699e'
down_revision: Union[str, Sequence[str], None] = 'ba732ba4559b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('study_plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_plan_id', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('estimated_time', sa.Integer(), nullable=False),
    sa.Column('subtopics', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['study_plan_id'], ['study_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_plan_items')
    op.drop_table('study_plans')
    # ### end Alembic commands ###
